on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: ArloL/actions/.github/actions/hello@v2408.0.102
      with:
        name: ${{ inputs.name }}
